spring:
  application:
    name: WRTestTask
  datasource:
    url: jdbc:postgresql://db:5432/WRTTDatabase
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    ru.alex9043.wrtesttask: DEBUG
  threshold:
    console: INFO
    file: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs